"""Alcatrazer CLI entry point.

Usage:
    alcatrazer init        — one-time: wizards + config + recipe on disk
    alcatrazer start       — build (if needed) + start the workspace container
    alcatrazer stop        — stop the running workspace container
    alcatrazer test        — run bundled test suite to verify installation
    alcatrazer --version   — print the version (also accepts -V)

Help is available globally (`alcatrazer --help` or `-h`) and per subcommand
(`alcatrazer start --help`, etc.) — both auto-generated by argparse.
"""

import argparse
import sys
import unittest
from pathlib import Path

from alcatrazer import __version__
from alcatrazer import start as start_module


def run_tests(smoke: bool = False) -> int:
    """Run the bundled test suite. Returns 0 on success, 1 on failure."""
    package_dir = Path(__file__).resolve().parent
    loader = unittest.TestLoader()
    suite = loader.discover(str(package_dir / "tests"))
    if smoke:
        # Include Docker integration tests (require Docker to be set up)
        integration_suite = loader.discover(str(package_dir / "integration_tests"))
        suite.addTests(integration_suite)
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    return 0 if result.wasSuccessful() else 1


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="alcatrazer",
        description="Alcatrazer — secure AI agent workspace.",
        epilog="https://github.com/greg-latuszek/alcatrazer",
    )
    parser.add_argument(
        "-V",
        "--version",
        action="version",
        version=f"alcatrazer {__version__}",
    )

    subparsers = parser.add_subparsers(dest="command", required=False)

    subparsers.add_parser(
        "init",
        help="One-time interactive setup (wizards + config + recipe)",
    )

    start_parser = subparsers.add_parser(
        "start",
        help="Build (if needed) and start the workspace container",
    )
    start_parser.add_argument(
        "--run-selftest",
        action="store_true",
        help=(
            "After start succeeds, run the bundled security self-tests "
            "(phantom UID, credential isolation, docker socket absence, …) "
            "against the running Alcatraz."
        ),
    )
    subparsers.add_parser(
        "stop",
        help="Stop the running workspace container",
    )

    test_parser = subparsers.add_parser(
        "test",
        help="Run bundled tests to verify installation",
    )
    test_parser.add_argument(
        "--smoke",
        action="store_true",
        help="Also run Docker integration tests (requires Docker)",
    )

    return parser


def main():
    parser = _build_parser()
    args = parser.parse_args()

    # `alcatrazer` alone — print help, exit 0. (argparse only errors on
    # an unknown subcommand; omitting the subcommand is allowed.)
    if args.command is None:
        parser.print_help()
        return

    if args.command == "init":
        sys.exit(start_module.cmd_init(Path.cwd()))
    elif args.command == "start":
        rc = start_module.cmd_start(Path.cwd())
        if rc == 0 and args.run_selftest:
            rc = start_module.cmd_selftest(Path.cwd())
        sys.exit(rc)
    elif args.command == "stop":
        sys.exit(start_module.cmd_stop(Path.cwd()))
    elif args.command == "test":
        sys.exit(run_tests(smoke=args.smoke))


if __name__ == "__main__":
    main()
