"""The `alcatrazer start` command — primary entry point for daily work.

Steps 3a-3h so far: route on `.alcatrazer/` presence; in the first-time
branch verify we are at a git repo root; helpers to read + prompt for the
promotion identity; wizard that collects the coding-environment answers
(languages, OS packages, startup commands); writers that persist the
answers to coding-environment.toml, .alcatrazer/config.toml, and
.env.example; writer that appends alcatrazer patterns to .git/info/exclude;
extractor that copies the installed alcatrazer package tree into
.alcatrazer/src/alcatrazer/. Backend-specific artifacts (Dockerfile,
entrypoint.sh) are generated by the sandbox adapter via `Alcatraz.
generate_prison()` (DockerPrison for MVP) — this module stays backend-
agnostic. Workspace name generation and its persistence to .alcatrazer/
workspace-dir are covered by alcatrazer.identity. Steps 3i-3k fill in the
remaining first-time work. Step 4 handles subsequent-run.
"""

import secrets
import shutil
import subprocess
import sys
import tomllib
import unittest
from pathlib import Path

from alcatrazer import identity, snapshot
from alcatrazer.alcatraz import Alcatraz, PrisonBuildError, PrisonStartError
from alcatrazer.languages import SUPPORTED_LANGUAGES


def cmd_start(project_dir: Path) -> int:
    """Route to first-time setup or subsequent-run based on project state."""
    if not (project_dir / ".alcatrazer").exists():
        return _first_time_setup(project_dir)
    return _subsequent_run(project_dir)


def _first_time_setup(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """Orchestrate the full first-time setup pipeline (Step 3).

    Wires together the Step 3 substep helpers in the order mandated by the
    install plan:

      3b — git repo guard
      3c — promotion identity prompt
      3d — coding-environment wizard
      3e — config-file writers (coding-environment.toml, .alcatrazer/config.toml,
           .env.example)
      3f — workspace name + .git/info/exclude patterns
      3g — package source extraction into .alcatrazer/src/alcatrazer/
      3i (symlink) — .alcatrazer/python -> sys.executable
      3h — prison recipe (Dockerfile + entrypoint.sh)
      3i (build) — docker build (phantom UID detected inside)
      3j — workspace dir + git init + agent identity + flat snapshot
      3k — start container + run startup commands + save .last snapshot

    PrisonBuildError / PrisonStartError are caught, formatted per the
    "Build & Startup Error Handling" contract, and returned as non-zero.
    """
    # 3b — git root guard.
    if not (project_dir / ".git").exists():
        print("alcatrazer must be run from a git repository root.", file=sys.stderr)
        return 1

    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    print("No alcatrazer setup found. Starting interactive setup...")
    print()

    # 3c — promotion identity.
    name, email = ask_promotion_identity(project_dir)

    # 3d — coding environment (languages, OS packages, startup commands).
    coding_env = ask_coding_environment()

    # 3e — config files.
    print()
    print("Writing configuration...")
    coding_env_path = write_coding_environment_toml(project_dir, coding_env)
    write_alcatrazer_config(project_dir, name, email, coding_env_file=coding_env_path.name)
    write_env_example(project_dir)

    # 3f — workspace dir name + .git/info/exclude patterns.
    workspace_name = identity.generate_workspace_dir_name()
    alcatrazer_dir = project_dir / ".alcatrazer"
    identity.store_workspace_dir(str(alcatrazer_dir), workspace_name)
    write_git_exclude(project_dir, workspace_name)

    # 3g — extract package source for trust (readable install + bundled tests).
    extract_package_source(project_dir)

    # 3i (symlink part) — stable python path for the daemon.
    write_python_symlink(project_dir)

    # 3h — generate prison recipe (backend-specific: Dockerfile + entrypoint.sh
    # for DockerPrison).
    print()
    print("Generating container recipe...")
    prison.generate_prison(coding_env)

    # 3i (build part) — build the image. Phantom UID detection happens inside.
    print("Building container image...")
    try:
        prison.build()
    except PrisonBuildError as e:
        print("ERROR: container image build failed.", file=sys.stderr)
        if e.stdout:
            print(e.stdout, file=sys.stderr)
        if e.stderr:
            print(e.stderr, file=sys.stderr)
        print(
            "→ Check [os] packages and [languages.*] in coding-environment.toml.",
            file=sys.stderr,
        )
        return 1

    # 3j — create workspace dir + git init + random agent identity + flat snapshot.
    print("Creating workspace snapshot...")
    create_workspace(project_dir, workspace_name)

    # 3k — start container + run [startup] commands + save .last.
    print("Starting container...")
    try:
        prison.start()
    except PrisonStartError as e:
        print("ERROR: container start failed.", file=sys.stderr)
        if e.stdout:
            print(e.stdout, file=sys.stderr)
        if e.stderr:
            print(e.stderr, file=sys.stderr)
        return 1

    startup_commands = coding_env.get("startup", {}).get("commands", [])
    if startup_commands:
        print("Running startup commands...")
    rc = run_startup_commands(prison, startup_commands)
    if rc == 0:
        save_coding_environment_snapshot(project_dir)
        print()
        print("Ready.")
    return rc


def read_git_identity(project_dir: Path) -> tuple[str | None, str | None]:
    """Return (name, email) from git config — local first, global fallback, per field."""

    def get(scope: str, key: str) -> str | None:
        result = subprocess.run(
            ["git", "config", f"--{scope}", "--get", key],
            cwd=project_dir,
            capture_output=True,
            text=True,
        )
        value = result.stdout.strip()
        return value if result.returncode == 0 and value else None

    name = get("local", "user.name") or get("global", "user.name")
    email = get("local", "user.email") or get("global", "user.email")
    return name, email


def ask_promotion_identity(project_dir: Path) -> tuple[str, str]:
    """Prompt the user for the promotion identity, offering the detected one as default."""
    name, email = read_git_identity(project_dir)
    if name and email:
        print(f"Detected git identity: {name} <{email}>")
        answer = input("Use for promoted commits? [Y/n] ").strip().lower()
        if answer in ("", "y", "yes"):
            return name, email

    print("Please enter the identity to use for promoted commits.")
    entered_name = input("Name: ").strip()
    entered_email = input("Email: ").strip()
    return entered_name, entered_email


def _ask_version(language: str) -> str:
    while True:
        version = input(f"  Version for {language}: ").strip()
        if not version:
            print("    Version is required.")
            continue
        if version.lower() == "latest":
            print('    Pin a concrete version — "latest" is not allowed.')
            continue
        return version


def _ask_manager(language: str) -> str | None:
    """Return the chosen manager, or None when it is the language default."""
    lang = SUPPORTED_LANGUAGES[language]
    managers = lang["managers"]
    default = lang["default_manager"]
    if len(managers) == 1:
        return None
    options = " / ".join(f"[{m}]" if m == default else m for m in managers)
    while True:
        choice = input(f"  Package manager for {language}? {options}: ").strip()
        if not choice:
            return None
        if choice in managers:
            return None if choice == default else choice
        print(f"    Unknown manager '{choice}' for {language}.")


def ask_languages() -> dict[str, dict]:
    """Ask which languages the project uses; collect version + manager for each."""
    supported = ", ".join(SUPPORTED_LANGUAGES)
    while True:
        print(f"What languages does this project use? (supported: {supported})")
        raw = input("Languages (comma-separated): ").strip()
        if not raw:
            print("  At least one language is required.")
            continue
        names = [p.strip().lower() for p in raw.split(",") if p.strip()]
        unknown = [n for n in names if n not in SUPPORTED_LANGUAGES]
        if unknown:
            print(f"  Unknown languages: {', '.join(unknown)}")
            continue
        break

    result: dict[str, dict] = {}
    for name in names:
        version = _ask_version(name)
        manager = _ask_manager(name)
        entry: dict = {"version": version}
        if manager is not None:
            entry["manager"] = manager
        result[name] = entry
    return result


def ask_os_packages() -> list[str]:
    """Optional list of apt-get packages. Accepts comma or whitespace separated."""
    raw = input("Any system packages needed? (e.g. libpq-dev ffmpeg; empty for none): ").strip()
    if not raw:
        return []
    return [p for p in raw.replace(",", " ").split() if p]


def ask_startup_commands() -> list[str]:
    """Commands to run after container start — one per line, empty line ends input."""
    print("Commands to run after container start (one per line, empty line to finish):")
    commands: list[str] = []
    while True:
        cmd = input("> ").strip()
        if not cmd:
            break
        commands.append(cmd)
    return commands


def ask_coding_environment() -> dict:
    """Collect the full coding-environment.toml structure interactively.

    Sections are returned in canonical TOML order (os, languages, startup);
    empty optional sections are omitted.
    """
    langs = ask_languages()
    os_pkgs = ask_os_packages()
    startup = ask_startup_commands()

    result: dict = {}
    if os_pkgs:
        result["os"] = {"packages": os_pkgs}
    if langs:
        result["languages"] = langs
    if startup:
        result["startup"] = {"commands": startup}
    return result


def _format_toml_string(value: str) -> str:
    """Render a Python str as a TOML basic string (double-quoted, escaped)."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _format_toml_list(values: list[str]) -> str:
    """Render a list of strings as an inline or multi-line TOML array."""
    if not values:
        return "[]"
    items = [_format_toml_string(v) for v in values]
    inline = "[" + ", ".join(items) + "]"
    if len(inline) <= 72:
        return inline
    return "[\n    " + ",\n    ".join(items) + ",\n]"


def _render_coding_environment(data: dict) -> str:
    """Serialize a coding-environment dict to TOML text. Zero alcatrazer branding."""
    lines = [
        "# Coding environment for this repository.",
        "# Sections run in dependency order: OS packages are installed first,",
        "# then language runtimes and managers, then post-start commands.",
        "",
    ]
    if "os" in data:
        lines.append("[os]")
        lines.append(f"packages = {_format_toml_list(data['os'].get('packages', []))}")
        lines.append("")
    if "languages" in data:
        for lang, cfg in data["languages"].items():
            lines.append(f"[languages.{lang}]")
            lines.append(f"version = {_format_toml_string(cfg['version'])}")
            if "manager" in cfg:
                lines.append(f"manager = {_format_toml_string(cfg['manager'])}")
            lines.append("")
    if "startup" in data:
        lines.append("[startup]")
        lines.append(f"commands = {_format_toml_list(data['startup'].get('commands', []))}")
        lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def write_coding_environment_toml(project_dir: Path, data: dict) -> Path:
    """Write coding-environment.toml at repo root; append hex suffix on collision."""
    target = project_dir / "coding-environment.toml"
    if target.exists():
        suffix = secrets.token_hex(2)
        target = project_dir / f"coding-environment-{suffix}.toml"
    target.write_text(_render_coding_environment(data))
    return target


def write_alcatrazer_config(
    project_dir: Path,
    name: str,
    email: str,
    coding_env_file: str = "coding-environment.toml",
) -> Path:
    """Write .alcatrazer/config.toml by line-rewriting the packaged template."""
    alcatrazer_dir = project_dir / ".alcatrazer"
    alcatrazer_dir.mkdir(parents=True, exist_ok=True)
    template_path = Path(__file__).parent / "templates" / "alcatrazer-config.toml"
    out_lines: list[str] = []
    for line in template_path.read_text().splitlines():
        if line.startswith("coding_environment_file = "):
            out_lines.append(f"coding_environment_file = {_format_toml_string(coding_env_file)}")
        elif line.startswith("name = "):
            out_lines.append(f"name = {_format_toml_string(name)}")
        elif line.startswith("email = "):
            out_lines.append(f"email = {_format_toml_string(email)}")
        else:
            out_lines.append(line)
    target = alcatrazer_dir / "config.toml"
    target.write_text("\n".join(out_lines) + "\n")
    return target


def write_env_example(project_dir: Path) -> Path | None:
    """Write a generic .env.example at repo root; skip and return None if it exists."""
    target = project_dir / ".env.example"
    if target.exists():
        return None
    target.write_text(
        "# Example environment variables for this project.\n"
        "# Copy to .env and fill in your values.\n"
        "# .env should stay out of version control; .env.example is committed.\n"
    )
    return target


def run_startup_commands(prison: Alcatraz, commands: list[str]) -> int:
    """Run each `[startup]` command inside the prison, fail-fast on first error.

    Each toml entry is a single shell string, so it is invoked as
    `bash -c <cmd>` — lets pipes, redirections, and multi-word commands
    behave as the user wrote them. Progress goes to stdout; on failure a
    pointer to the offending index + command goes to stderr. Returns 0 on
    full success or the failing exit code.
    """
    for i, cmd in enumerate(commands, 1):
        print(f"→ Running startup command #{i}: {cmd}")
        rc = prison.exec(["bash", "-c", cmd])
        if rc != 0:
            print(
                f"ERROR: startup command #{i} failed ({cmd!r}) — exit {rc}.",
                file=sys.stderr,
            )
            print(
                "→ Check the [startup] block in coding-environment.toml.",
                file=sys.stderr,
            )
            return rc
    return 0


def save_coding_environment_snapshot(project_dir: Path) -> Path:
    """Copy the current coding-environment file to .alcatrazer/coding-environment.toml.last.

    The source filename is read from .alcatrazer/config.toml's
    `coding_environment_file` pointer (supports hex-suffixed collisions).
    The target name is always canonical (`coding-environment.toml.last`),
    so Step 4 can diff against a fixed path.
    """
    alcatrazer_dir = project_dir / ".alcatrazer"
    with open(alcatrazer_dir / "config.toml", "rb") as f:
        config = tomllib.load(f)
    source_name = config.get("coding_environment_file", "coding-environment.toml")
    source = project_dir / source_name
    target = alcatrazer_dir / "coding-environment.toml.last"
    shutil.copy(source, target)
    return target


def create_workspace(project_dir: Path, workspace_name: str) -> Path:
    """Create the inner workspace for the agent (Step 3j).

    - Creates `project_dir / workspace_name` (the leading dot is expected
      to be part of `workspace_name`, matching identity.generate_workspace_dir_name).
    - `git init`s it with a fresh history disconnected from the outer repo.
    - Generates + persists the random agent identity (or reuses an existing
      one) via identity.ensure_identity.
    - Wires the workspace-local git config: user.name / user.email from the
      stored identity, `commit.gpgsign false`; clears any host signing-key
      path so host state does not leak into the inner repo.
    - Takes a flat snapshot of the outer repo's default branch via
      snapshot.snapshot_workspace — files only, no history, single initial
      commit authored by the agent identity.

    Returns the workspace directory path.
    """
    workspace_dir = project_dir / workspace_name
    alcatrazer_dir = project_dir / ".alcatrazer"
    alcatrazer_dir.mkdir(parents=True, exist_ok=True)
    workspace_dir.mkdir(parents=True, exist_ok=True)

    subprocess.run(
        ["git", "init", str(workspace_dir)],
        capture_output=True,
        check=True,
    )

    name, email = identity.ensure_identity(str(alcatrazer_dir))

    def _wgit(*args: str) -> None:
        subprocess.run(
            ["git", "-C", str(workspace_dir), *args],
            capture_output=True,
            check=True,
        )

    _wgit("config", "--local", "user.name", name)
    _wgit("config", "--local", "user.email", email)
    _wgit("config", "--local", "commit.gpgsign", "false")
    # Defensive: clear any host signing-key references so they cannot leak
    # into the inner repo's config.
    _wgit("config", "--local", "user.signingkey", "")
    _wgit("config", "--local", "gpg.ssh.allowedSignersFile", "")

    snapshot.snapshot_workspace(str(project_dir), str(workspace_dir))

    return workspace_dir


def write_python_symlink(project_dir: Path) -> Path:
    """Symlink `.alcatrazer/python` → `sys.executable`.

    Gives the post-install daemon (and any other tooling that needs to call
    back into a host Python) a stable path to the resolved interpreter,
    independent of the user's shell at run time.
    """
    alcatrazer_dir = project_dir / ".alcatrazer"
    alcatrazer_dir.mkdir(parents=True, exist_ok=True)
    target = alcatrazer_dir / "python"
    if target.is_symlink() or target.exists():
        target.unlink()
    target.symlink_to(sys.executable)
    return target


_PACKAGE_IGNORE_PATTERNS = ("__pycache__", "*.pyc", "*.pyo")


def extract_package_source(
    project_dir: Path,
    source_dir: Path | None = None,
) -> Path:
    """Copy the alcatrazer package tree into .alcatrazer/src/alcatrazer/.

    Gives the user readable source and bundled tests. Compiled artifacts
    (__pycache__, .pyc, .pyo) are skipped. If the destination already
    exists (e.g., on re-run or during `alcatrazer upgrade`), it is removed
    first so stale files cannot linger from an older version.

    `source_dir` defaults to the installed package directory (Step 6
    upgrade passes a freshly-downloaded wheel's extracted tree instead).
    """
    if source_dir is None:
        source_dir = Path(__file__).parent
    dest = project_dir / ".alcatrazer" / "src" / "alcatrazer"
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source_dir, dest, ignore=shutil.ignore_patterns(*_PACKAGE_IGNORE_PATTERNS))
    return dest


_GIT_EXCLUDE_HEADER = "# alcatrazer patterns (written by alcatrazer start)"


def write_git_exclude(project_dir: Path, workspace_name: str) -> Path:
    """Append alcatrazer + workspace patterns to .git/info/exclude, idempotently.

    `workspace_name` is used verbatim (callers pass the full directory name,
    typically from `alcatrazer.identity.generate_workspace_dir_name()` which
    already includes the leading dot). We just append a trailing slash to
    form the directory pattern.
    """
    exclude_path = project_dir / ".git" / "info" / "exclude"
    exclude_path.parent.mkdir(parents=True, exist_ok=True)
    existing = exclude_path.read_text() if exclude_path.exists() else ""
    existing_lines = set(existing.splitlines())

    patterns = (".alcatrazer/", f"{workspace_name}/")
    missing = [p for p in patterns if p not in existing_lines]
    if not missing:
        return exclude_path

    prefix = existing
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    exclude_path.write_text(prefix + _GIT_EXCLUDE_HEADER + "\n" + "\n".join(missing) + "\n")
    return exclude_path


def coding_environment_changed(project_dir: Path) -> bool:
    """True when the current coding-environment file differs from .last.

    The source filename is read from .alcatrazer/config.toml's
    `coding_environment_file` pointer (supports hex-suffixed collisions).
    `.last` missing counts as changed.
    """
    alcatrazer_dir = project_dir / ".alcatrazer"
    with open(alcatrazer_dir / "config.toml", "rb") as f:
        config = tomllib.load(f)
    source = project_dir / config.get("coding_environment_file", "coding-environment.toml")
    last = alcatrazer_dir / "coding-environment.toml.last"
    if not last.exists():
        return True
    return source.read_text() != last.read_text()


def _load_coding_environment(project_dir: Path) -> dict:
    """Read config.toml pointer + parse the current coding-environment file."""
    alcatrazer_dir = project_dir / ".alcatrazer"
    with open(alcatrazer_dir / "config.toml", "rb") as f:
        config = tomllib.load(f)
    source = project_dir / config.get("coding_environment_file", "coding-environment.toml")
    with open(source, "rb") as f:
        return tomllib.load(f)


def cmd_selftest(project_dir: Path) -> int:
    """Run `--run-selftest`: execute the bundled security invariants against
    the Alcatraz just started at `project_dir`. Returns 0 on success or
    non-zero on failure (count of failures is shown by the test runner)."""
    from alcatrazer import selftest

    TestCase = selftest.make_alcatraz_selftest_testcase(project_dir)
    suite = unittest.TestLoader().loadTestsFromTestCase(TestCase)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


def cmd_stop(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """`alcatrazer stop` — idempotent container stop.

    Requires an existing alcatrazer setup (`.alcatrazer/`). Returns 0 on
    success or when the container is already stopped; 1 when there is no
    setup to stop.
    """
    if not (project_dir / ".alcatrazer").exists():
        print(
            "No alcatrazer setup in this repository — run `alcatrazer start` first.",
            file=sys.stderr,
        )
        return 1

    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    if not prison.is_running():
        print("Container is not running.")
        return 0

    prison.stop()
    print("Container stopped.")
    return 0


def _subsequent_run(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """Detect state and bring the workspace container into sync with the
    current coding-environment.toml.

    Branches on three signals:
      - prison.needs_rebuild(data) — would-be recipe vs on-disk
      - prison.is_running()        — container state
      - coding_environment_changed(project_dir) — toml vs .last snapshot

    Fast path: running + nothing changed → "already up to date".
    Otherwise: stop (if running), remove, build (if rebuild), start,
    run [startup] commands. `.last` refresh only on startup success so
    a retry sees the same drift.
    """
    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    coding_env = _load_coding_environment(project_dir)
    commands = coding_env.get("startup", {}).get("commands", [])

    rebuild = prison.needs_rebuild(coding_env)
    running = prison.is_running()
    toml_changed = coding_environment_changed(project_dir)

    if not rebuild and not toml_changed and running:
        print("Already running, environment up to date.")
        return 0

    if rebuild:
        print("coding-environment.toml changed — rebuilding image.")
        prison.generate_prison(coding_env)

    if running:
        prison.stop()
    prison.remove()

    if rebuild:
        prison.build()

    prison.start()
    rc = run_startup_commands(prison, commands)
    if rc == 0:
        save_coding_environment_snapshot(project_dir)
    return rc
