"""The `alcatrazer init` / `alcatrazer start` commands.

Two commands, two phases of the install:

- `cmd_init` — Steps 3b-3h. Runs the interactive wizards, writes configs +
  .env.example, extracts the package source, generates the sandbox recipe
  (Dockerfile + entrypoint.sh via `Alcatraz.generate_prison()`). Stops
  before `docker build`. This is the gate where the user populates `.env`
  or logs into Claude on the host — see "alcatrazer init" in
  install_method.md for the rationale.

- `cmd_start` — the daily command. Requires `.alcatrazer/` (produced by
  init). Routes on `prison.image_exists()`:
    - image missing → `_first_run_after_init` (Step 3.5: 3i/3j/3k).
    - image present → `_subsequent_run` (Step 4 drift detection).

Backend-specific artifacts (Dockerfile, entrypoint.sh) are generated by
the sandbox adapter via `Alcatraz.generate_prison()` (DockerPrison for
MVP) — this module stays backend-agnostic.
"""

import hashlib
import secrets
import shutil
import subprocess
import sys
import tomllib
import unittest
from pathlib import Path

from alcatrazer import identity, snapshot
from alcatrazer.alcatraz import Alcatraz, PrisonBuildError, PrisonStartError
from alcatrazer.daemon_lifecycle import (
    launch_daemon_and_print,
    print_shutdown_result,
    shutdown_sync_daemon,
)
from alcatrazer.languages import SUPPORTED_LANGUAGES

# --- Coding-environment schema version --------------------------------------
#
# Bumped when the structure of `coding-environment.toml` changes in an
# incompatible way. Files written before this field existed are treated as
# version 1 (backwards compat). An older alcatrazer encountering a newer
# schema raises UnsupportedSchemaVersionError rather than silently
# misreading.

CODING_ENV_SCHEMA_VERSION = 1


class UnsupportedSchemaVersionError(Exception):
    """coding-environment.toml declares a schema_version this alcatrazer
    cannot parse — almost always means the user needs to upgrade."""


def _validate_coding_env_schema_version(data: dict) -> None:
    """Reject coding-environment.toml configs we can't safely parse.

    - field absent → OK (treated as CODING_ENV_SCHEMA_VERSION; backwards compat)
    - positive int ≤ CODING_ENV_SCHEMA_VERSION → OK
    - everything else → UnsupportedSchemaVersionError

    The bool branch is explicit because bool is a subclass of int in Python
    (`isinstance(True, int)` is True), and `schema_version = true` should not
    silently slip through as `1`.
    """
    if "schema_version" not in data:
        return
    value = data["schema_version"]
    if isinstance(value, bool) or not isinstance(value, int):
        raise UnsupportedSchemaVersionError(
            f"coding-environment.toml: schema_version must be an integer, "
            f"got {value!r} ({type(value).__name__})."
        )
    if value < 1:
        raise UnsupportedSchemaVersionError(
            f"coding-environment.toml: schema_version must be >= 1, got {value}."
        )
    if value > CODING_ENV_SCHEMA_VERSION:
        raise UnsupportedSchemaVersionError(
            f"coding-environment.toml declares schema_version={value}, but "
            f"this alcatrazer only supports up to {CODING_ENV_SCHEMA_VERSION}. "
            f"Upgrade alcatrazer (e.g. `uv tool upgrade alcatrazer` or "
            f"`pipx upgrade alcatrazer`)."
        )


# --- Detection of alcatrazer-generated coding-environment.toml --------------
#
# Used by `cmd_init` to recognize a `coding-environment.toml` produced by a
# previous run of the wizard, so the user can reuse it instead of orphaning
# it with a hex-suffix duplicate. Detection is schema-version-aware: each
# schema's `_render_coding_environment` may emit different header text, and
# we need to match what the file's declared `schema_version` actually wrote.
#
# When v2 lands with `[provision]`, add a `2: (...)` entry alongside the v1
# tuple — the dict is the single source of truth, no detection-logic refactor
# required. The `GeneratedMarkersTableTests.test_current_schema_has_marker_entry`
# guard catches a missing entry at test time.

_GENERATED_MARKERS_BY_SCHEMA: dict[int, tuple[str, ...]] = {
    1: (
        "# Coding environment definition for this repository.",
        "# Sections follow dependency order: OS -> languages -> startup.",
    ),
}


def _load_existing_alcatrazer_config(project_dir: Path) -> dict | None:
    """Return parsed `coding-environment.toml` if it looks alcatrazer-
    generated, None otherwise.

    Detection: read the file (if present), parse it, look up its
    `schema_version` (defaulting to v1 to match the validator's
    backwards-compat semantics), then require BOTH header markers from
    `_GENERATED_MARKERS_BY_SCHEMA[version]` to appear in the file. Any
    failure along the way (missing file, invalid TOML, unknown version,
    markers absent) returns None — the caller falls back to today's
    hex-suffix behavior, which never clobbers user content.

    Conservative threshold (require both markers) is deliberate. False
    positives let an already-good file be "reused" with no real harm;
    false negatives revert to hex-suffix fallback — annoying but never
    destructive.
    """
    target = project_dir / "coding-environment.toml"
    if not target.exists():
        return None
    try:
        with open(target, "rb") as f:
            data = tomllib.load(f)
    except tomllib.TOMLDecodeError:
        return None
    version = data.get("schema_version", CODING_ENV_SCHEMA_VERSION)
    if isinstance(version, bool) or not isinstance(version, int):
        return None
    markers = _GENERATED_MARKERS_BY_SCHEMA.get(version)
    if markers is None:
        return None
    content = target.read_text()
    if not all(marker in content for marker in markers):
        return None
    return data


def cmd_start(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """`alcatrazer start` — build (if needed) and run the workspace container.

    Requires `cmd_init` to have run already (produces `.alcatrazer/`). Routes
    on "is first-run setup still needed?" — answered by TWO signals, because
    image and workspace have independent lifetimes:

    - **Image.** Persists across `alcatrazer clear` (we only remove the
      container). But a user running `docker image prune`, or a fresh CI
      checkout, can see the image go away.
    - **Workspace.** Persists across both stop and clear (host-side dir).
      But a user running `rm -rf .devspace-xxx` removes it.

    If EITHER is missing we hit the first-run branch so the missing piece
    gets (re-)created. `_first_run_after_init` is itself idempotent: it
    skips `prison.build()` when the image is already present.

    Previous routing (image-only) failed in the "stale image + no
    workspace" case — e.g., prior test run left the image behind and the
    current tempdir has no workspace → subsequent_run got entered with no
    inner repo, daemon failed to find workspace-dir/.git.
    """
    if not (project_dir / ".alcatrazer").exists():
        print(
            "No alcatrazer setup in this repository — run `alcatrazer init` first.",
            file=sys.stderr,
        )
        return 1

    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    alcatraz_dir = project_dir / ".alcatrazer"
    workspace_name = identity.load_workspace_dir(str(alcatraz_dir))
    workspace_ready = (
        workspace_name is not None and (project_dir / workspace_name / ".git").is_dir()
    )
    try:
        # Phase 1.2.6: route on `image_matches(recipe_hash)` instead of
        # bare `image_exists()`. Catches stale-image scenarios that
        # today's "image present → reuse" check trusts blindly (e.g.
        # `rm -rf .alcatrazer/` left an old image in place; the new
        # init regenerates the Dockerfile but the running image still
        # carries the OLD config_hash label). The schema validator can
        # also raise UnsupportedSchemaVersionError when loading the
        # coding-environment, so all of this lives inside the try.
        coding_env = _load_coding_environment(project_dir)
        current_hash = prison.recipe_hash(coding_env)
        if not prison.image_matches(current_hash) or not workspace_ready:
            return _first_run_after_init(project_dir, prison=prison)
        return _subsequent_run(project_dir, prison=prison)
    except UnsupportedSchemaVersionError as e:
        # Both routing branches load coding-environment.toml as their first
        # real step; either can raise this. We print the validator's own
        # message — it already names the offending version and tells the
        # user to upgrade alcatrazer — and skip the traceback so the
        # config issue doesn't read like a tool crash.
        print(f"ERROR: {e}", file=sys.stderr)
        return 1


def _host_has_claude_creds() -> bool:
    """True if the host has Claude Code creds at ~/.claude/.credentials.json.

    When present, `DockerPrison.start` mounts the file read-only into the
    container — no `.env` auth needed. When absent, the user needs to
    populate `ANTHROPIC_API_KEY` in `.env` before `alcatrazer start`.
    Factored out so tests can patch it without touching the real HOME.
    """
    return (Path.home() / ".claude" / ".credentials.json").exists()


def cmd_init(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """`alcatrazer init` — one-time disk setup (Steps 3b-3h).

    Runs the wizards, writes configs + .env.example, extracts the package
    source, generates the sandbox recipe. Stops before `docker build` so
    the user can populate AI credentials before `alcatrazer start`.

    Guards:
      - `.alcatrazer/` already present → error (re-running init is not a
        daily operation; edit `coding-environment.toml` and `start` instead).
      - Not a git repo root → error per the "must be at repo root" contract.
    """
    alcatrazer_dir = project_dir / ".alcatrazer"
    if alcatrazer_dir.exists():
        print(
            "This repository is already initialized (.alcatrazer/ exists). "
            "Edit coding-environment.toml and run `alcatrazer start` to apply changes.",
            file=sys.stderr,
        )
        return 1

    if not (project_dir / ".git").exists():
        print("alcatrazer must be run from a git repository root.", file=sys.stderr)
        return 1

    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    # `.alcatrazer/` is cmd_init's own directory — create it explicitly
    # up front rather than relying on a downstream writer's mkdir side
    # effect. Keeps step ordering safe to reshuffle.
    alcatrazer_dir.mkdir(parents=True, exist_ok=True)

    print("Starting interactive setup...")
    print()
    _print_init_intro()

    # 3c — promotion identity.
    name, email = ask_promotion_identity(project_dir)

    # 3d — coding environment (languages, OS packages, startup commands).
    # Phase 1.2.3: if a previous-run alcatrazer-generated config still
    # exists in the repo, offer to reuse it (skip the wizard, leave the
    # file untouched) rather than orphan it with a hex-suffix duplicate.
    # User-authored files are detected as "not ours" and bypass this
    # branch, preserving today's never-clobber-user-content guarantee.
    existing = _load_existing_alcatrazer_config(project_dir)
    reuse_existing = False
    overwrite_existing = False
    if existing is not None:
        print()
        print("Detected existing coding-environment.toml from a previous alcatrazer install.")
        answer = input("Reuse it as-is? [Y/n] ").strip().lower()
        if answer in ("", "y", "yes"):
            print("Reusing coding-environment.toml.")
            coding_env = existing
            reuse_existing = True
        else:
            coding_env = ask_coding_environment()
            answer = input("Overwrite existing coding-environment.toml? [y/N] ").strip().lower()
            overwrite_existing = answer in ("y", "yes")
    else:
        coding_env = ask_coding_environment()

    # 3f — workspace dir name + .git/info/exclude patterns. (Pulled ahead
    # of 3e config writes so `.env.example`'s marker block can embed the
    # workspace name — see _env_example_markers for why.)
    workspace_name = identity.generate_workspace_dir_name()
    identity.store_workspace_dir(str(alcatrazer_dir), workspace_name)
    write_git_exclude(project_dir, workspace_name)

    # 3e — config files.
    print()
    print("Writing configuration...")
    if reuse_existing:
        # Reuse path: don't re-render; the existing file is the source
        # of truth. Point the alcatrazer config at it by name.
        coding_env_path = project_dir / "coding-environment.toml"
    else:
        coding_env_path = write_coding_environment_toml(
            project_dir, coding_env, overwrite=overwrite_existing
        )
    write_alcatrazer_config(project_dir, name, email, coding_env_file=coding_env_path.name)
    write_env_example(project_dir, workspace_name)
    print(f"  {coding_env_path.name}  (commit to git — your team's workspace recipe)")
    print("  .alcatrazer/config.toml      (per-developer; auto-excluded from git)")
    print("  .env.example                 (commit to git — placeholders only, no secrets)")

    # 3g — extract package source for trust (readable install + bundled tests).
    extract_package_source(project_dir)

    # 3i (symlink part) — stable python path for the daemon.
    write_python_symlink(project_dir)

    # 3h — generate prison recipe (backend-specific: Dockerfile + entrypoint.sh
    # for DockerPrison).
    print()
    print("Generating Alcatraz recipe...")
    prison.generate_prison(coding_env)

    print()
    if _host_has_claude_creds():
        print("Claude credentials found on host — they will be used by Alcatraz.")
        print("Next: run `alcatrazer start` to build Alcatraz and run it with own git,")
        print("then `alcatrazer visit` to step inside.")
    else:
        print("Claude credentials not found at ~/.claude/.credentials.json.")
        print("Before running `alcatrazer start`, either:")
        print("  (a) run `claude` on your host to authenticate, or")
        print("  (b) copy .env.example to .env and fill in ANTHROPIC_API_KEY.")
        print()
        print("Then run `alcatrazer start` to build Alcatraz and run it with own git,")
        print("then `alcatrazer visit` to step inside.")
    return 0


def _first_run_after_init(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """Step 3.5: the `alcatrazer start` first-run branch.

      3i (build) — docker build (phantom UID detected inside)
      3j — workspace dir + git init + agent identity + flat snapshot
      3k — start container + run [startup] commands + save .last snapshot

    PrisonBuildError / PrisonStartError are caught, formatted per the
    "Build & Startup Error Handling" contract, and returned as non-zero.
    """
    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    alcatrazer_dir = project_dir / ".alcatrazer"
    coding_env = _load_coding_environment(project_dir)

    workspace_name = identity.load_workspace_dir(str(alcatrazer_dir))

    # Phase 1.2.6: skip build only when the image carries the
    # alcatrazer.config_hash matching the current recipe. Bare
    # `image_exists()` would trust an older image left over from a
    # different config — the bug reported by users who'd done
    # `rm -rf .alcatrazer/` and re-run `init`. `image_matches` answers
    # the right question ("is this image current?") instead of
    # "is there any image?".
    current_hash = prison.recipe_hash(coding_env)
    if not prison.image_matches(current_hash):
        print("Building Alcatraz image...")
        try:
            prison.build()
        except PrisonBuildError as e:
            print("ERROR: Alcatraz image build failed.", file=sys.stderr)
            if e.stdout:
                print(e.stdout, file=sys.stderr)
            if e.stderr:
                print(e.stderr, file=sys.stderr)
            print(
                "→ Check [os] packages and [languages.*] in coding-environment.toml.",
                file=sys.stderr,
            )
            return 1
    else:
        print("Alcatraz image already present — skipping build.")

    print("Creating workspace snapshot...")
    create_workspace(project_dir, workspace_name)

    print("Starting Alcatraz...")
    try:
        prison.start()
    except PrisonStartError as e:
        print("ERROR: Alcatraz start failed.", file=sys.stderr)
        if e.stdout:
            print(e.stdout, file=sys.stderr)
        if e.stderr:
            print(e.stderr, file=sys.stderr)
        return 1

    startup_commands = coding_env.get("startup", {}).get("commands", [])
    if startup_commands:
        print("Running startup commands...")
    rc = run_startup_commands(prison, startup_commands)
    if rc == 0:
        save_coding_environment_snapshot(project_dir)
        save_env_snapshot(project_dir)
        launch_daemon_and_print(project_dir)
        print()
        # Phase 1.2.5: point users at the new way to step inside.
        print("Ready. To enter the Alcatraz: alcatrazer visit")
    return rc


def read_git_identity(project_dir: Path) -> tuple[str | None, str | None]:
    """Return (name, email) from git config — local first, global fallback, per field."""

    def get(scope: str, key: str) -> str | None:
        result = subprocess.run(
            ["git", "config", f"--{scope}", "--get", key],
            cwd=project_dir,
            capture_output=True,
            text=True,
        )
        value = result.stdout.strip()
        return value if result.returncode == 0 and value else None

    name = get("local", "user.name") or get("global", "user.name")
    email = get("local", "user.email") or get("global", "user.email")
    return name, email


def _print_init_intro() -> None:
    """Print the introductory diagram + explanation for `alcatrazer init`.

    Once at the top of the wizard so subsequent prompts can use the
    terms `promote`, `Alcatraz`, and `agents` without redefining them.
    The diagram puts `your repo` and `Alcatraz (agents repo)` in
    parallel structure with parity labels for identity + credentials,
    so the contrast lands at a glance.
    """
    print("What this sets up:")
    print()
    print("   your repo  <--- promote ---  Alcatraz (agents repo)")
    print("   ---------                    ---------------------")
    print("   YOUR identity                fake throwaway identity")
    print("   YOUR git credentials         no credentials, no SSH keys")
    print()
    print("Agents commit inside Alcatraz; a daemon promotes commits back to")
    print("your repo, re-authored as YOU. Agents cannot push — only you can.")
    print()
    print("This wizard writes coding-environment.toml; you can edit it before")
    print("running `alcatrazer start` if you want to tweak.")
    print()


def ask_promotion_identity(project_dir: Path) -> tuple[str, str]:
    """Prompt the user for the promotion identity, offering the detected one as default."""
    print("=== Promotion identity ===")
    print("Re-authored onto agent commits when the daemon promotes them to")
    print("your repo (see diagram above).")
    print()
    name, email = read_git_identity(project_dir)
    if name and email:
        print(f"Detected git identity: {name} <{email}>")
        answer = input("Use for promoted commits? [Y/n] ").strip().lower()
        if answer in ("", "y", "yes"):
            return name, email

    print("Please enter the identity to use for promoted commits.")
    entered_name = input("Name: ").strip()
    entered_email = input("Email: ").strip()
    return entered_name, entered_email


def _ask_version(language: str) -> str:
    tip = SUPPORTED_LANGUAGES[language].get("version_tip")
    if tip:
        # Wrap to a comfortable terminal width with hanging indent so
        # continuation lines align under the first character of the tip.
        # Blank line goes BEFORE the tip (Phase 1.2.3): visually groups
        # the tip with the upcoming `Version for X:` prompt rather than
        # orphaning it to the previous prompt's answer.
        import textwrap

        print()
        print(
            textwrap.fill(
                tip,
                width=72,
                initial_indent="  Tip: ",
                subsequent_indent="       ",
            )
        )
    while True:
        version = input(f"  Version for {language}: ").strip()
        if not version:
            print("    Version is required.")
            continue
        if version.lower() == "latest":
            print('    Pin a concrete version — "latest" is not allowed.')
            continue
        return version


def _ask_manager(language: str) -> str:
    """Return the chosen manager — always a string, never None.

    Phase 1.2.4: previously returned None for default-accepted or
    single-manager cases, which left `manager` out of the result dict
    and therefore out of the generated TOML AND out of mise install
    decisions. Now the resolved value is always returned, so the wizard
    output always carries the manager that downstream code (TOML write,
    mise install) needs to see.

    Single-manager case: skip the prompt, return the lone option.
    Multi-manager case: print `manager_tip` (if declared, blank line
    BEFORE — same layout convention as `_ask_version`), then prompt;
    empty input returns the language default.
    """
    lang = SUPPORTED_LANGUAGES[language]
    managers = lang["managers"]
    default = lang["default_manager"]
    if len(managers) == 1:
        return managers[0]

    tip = lang.get("manager_tip")
    if tip:
        import textwrap

        print()
        print(
            textwrap.fill(
                tip,
                width=72,
                initial_indent="  Tip: ",
                subsequent_indent="       ",
            )
        )

    options = " / ".join(f"[{m}]" if m == default else m for m in managers)
    while True:
        choice = input(f"  Package manager for {language}? {options}: ").strip()
        if not choice:
            return default
        if choice in managers:
            return choice
        print(f"    Unknown manager '{choice}' for {language}.")


def ask_languages() -> dict[str, dict]:
    """Ask which languages the project uses; collect version + manager for each."""
    print()
    print("=== Languages ===")
    print("Languages you list here are baked into Alcatraz so agents have a")
    print("ready dev environment from day one. Stored in coding-environment.toml;")
    print("edit before `alcatrazer start` to tweak the picks below.")
    print()
    supported = ", ".join(SUPPORTED_LANGUAGES)
    while True:
        print(f"What languages does this project use? (supported: {supported})")
        raw = input("Languages (comma-separated): ").strip()
        if not raw:
            print("  At least one language is required.")
            continue
        names = [p.strip().lower() for p in raw.split(",") if p.strip()]
        unknown = [n for n in names if n not in SUPPORTED_LANGUAGES]
        if unknown:
            print(f"  Unknown languages: {', '.join(unknown)}")
            continue
        break

    result: dict[str, dict] = {}
    for name in names:
        version = _ask_version(name)
        manager = _ask_manager(name)
        # Phase 1.2.4: `manager` is always a string now (the resolved
        # value, default or override). Always store it.
        result[name] = {"version": version, "manager": manager}
    return result


def ask_os_packages() -> list[str]:
    """Optional list of apt-get packages. Accepts comma or whitespace separated."""
    print()
    print("=== System packages (optional) ===")
    print("Extra apt packages baked into Alcatraz at build time, alongside")
    print("the languages above.")
    raw = input("Any system packages needed? (e.g. libpq-dev ffmpeg; empty for none): ").strip()
    if not raw:
        return []
    return [p for p in raw.replace(",", " ").split() if p]


def ask_startup_commands() -> list[str]:
    """Commands to run after Alcatraz start — one per line, empty line ends input."""
    print()
    print("=== Startup commands (optional) ===")
    print("Run every time Alcatraz boots — typically `uv sync`, `npm install`,")
    print("or similar dev-env prep. These are NOT baked in (unlike languages")
    print("above).")
    print()
    print("Commands to run after Alcatraz start (one per line, empty line to finish):")
    commands: list[str] = []
    while True:
        cmd = input("> ").strip()
        if not cmd:
            break
        commands.append(cmd)
    return commands


def ask_coding_environment() -> dict:
    """Collect the full coding-environment.toml structure interactively.

    Sections are returned in canonical TOML order (os, languages, startup);
    empty optional sections are omitted.
    """
    langs = ask_languages()
    os_pkgs = ask_os_packages()
    startup = ask_startup_commands()

    result: dict = {}
    if os_pkgs:
        result["os"] = {"packages": os_pkgs}
    if langs:
        result["languages"] = langs
    if startup:
        result["startup"] = {"commands": startup}
    return result


def _format_toml_string(value: str) -> str:
    """Render a Python str as a TOML basic string (double-quoted, escaped)."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _format_toml_list(values: list[str]) -> str:
    """Render a list of strings as an inline or multi-line TOML array."""
    if not values:
        return "[]"
    items = [_format_toml_string(v) for v in values]
    inline = "[" + ", ".join(items) + "]"
    if len(inline) <= 72:
        return inline
    return "[\n    " + ",\n    ".join(items) + ",\n]"


# Commented-out syntax reference for each supported language. Emitted in
# the generated coding-environment.toml so a user who didn't pick (say)
# node at init time can uncomment the block later and run `alcatrazer start`
# without hunting for docs.
_EXAMPLE_LANGUAGE_BLOCKS: dict[str, list[str]] = {
    "python": ["# [languages.python]", '# version = "3.12"', '# manager = "uv"'],
    "node": ["# [languages.node]", '# version = "22"'],
    "rust": ["# [languages.rust]", '# version = "1.75"'],
    "go": ["# [languages.go]", '# version = "1.22"'],
    "dotnet": ["# [languages.dotnet]", '# version = "10.0.100"'],
    "java": ["# [languages.java]", '# version = "21"'],
}

_CODING_ENVIRONMENT_HEADER = [
    "# Coding environment definition for this repository.",
    "#",
    "# Describes what must exist before the project's own setup can run — OS",
    "# packages, language runtimes and their managers, and post-start commands.",
    "# Sections follow dependency order: OS -> languages -> startup.",
    "#",
    "# Edit freely. Changes to [os] or [languages] trigger a workspace rebuild",
    "# on the next run; changes to [startup] only trigger a restart.",
    "#",
    "# Language libraries (pip, npm, cargo, ...) do NOT belong here — they live",
    "# in the project's own manifests (requirements.txt, package.json, etc.)",
    "# and get installed by [startup] commands or by agents at runtime.",
]

_SCHEMA_VERSION_COMMENT = [
    "# File-format version. Bumped when the structure of this file changes",
    "# in an incompatible way. Older tooling refuses newer schemas rather",
    "# than silently misreading them. Leave at 1 unless you know why.",
]

_OS_SECTION_COMMENT = [
    "# System packages installed when the workspace is built.",
    "# Typical uses: compilation toolchains, shared libraries for native modules,",
    "# system tools that language packages cannot provide.",
]
_OS_EXAMPLE = ["# [os]", '# packages = ["build-essential", "libpq-dev"]']

_LANGUAGES_SECTION_COMMENT = [
    "# Language runtimes and package managers, one subtable per language.",
    '# `version` is required — pin to a concrete number, never "latest".',
    "# `manager` is optional — omit to use the language's standard manager.",
]

_STARTUP_SECTION_COMMENT = [
    "# Commands run after the workspace starts, in order. Fail-fast: a non-zero",
    "# exit stops the remaining commands. Use for installing project dependencies",
    "# from the repo's own manifests, configuring frameworks, arbitrary setup.",
]
_STARTUP_EXAMPLE = [
    "# [startup]",
    "# commands = [",
    '#     "uv sync",',
    '#     "npm install",',
    "# ]",
]


def _render_coding_environment(data: dict) -> str:
    """Serialize a coding-environment dict to rich, comment-heavy TOML.

    Intent: whatever the user picks via the init wizard, the generated
    file also carries enough inline documentation + commented-out
    examples that the user can edit the toml directly later ("add rust",
    "add an [os] package", "wire up a [startup] command") and run
    `alcatrazer start` without consulting docs.

    Anti-leak discipline: this file is at the outer repo root, so it
    gets committed to the user's git AND snapshotted into /workspace.
    Zero `alcatraz` / `alcatrazer` strings, zero backend-specific
    vocabulary (no "container", no "image" — "workspace" is the neutral
    term that survives a future podman/sysbox/VM backend).
    """
    lines: list[str] = [*_CODING_ENVIRONMENT_HEADER, ""]

    # --- schema_version (top-level field, must precede any [section]) ---
    lines += _SCHEMA_VERSION_COMMENT
    lines.append(f"schema_version = {CODING_ENV_SCHEMA_VERSION}")
    lines.append("")

    # --- [os] -----------------------------------------------------------
    lines += _OS_SECTION_COMMENT
    os_packages = data.get("os", {}).get("packages", [])
    if os_packages:
        lines.append("[os]")
        lines.append(f"packages = {_format_toml_list(os_packages)}")
    else:
        lines += _OS_EXAMPLE
    lines.append("")

    # --- [languages.*] --------------------------------------------------
    lines += _LANGUAGES_SECTION_COMMENT
    languages = data.get("languages", {})
    for lang, cfg in languages.items():
        lines.append(f"[languages.{lang}]")
        lang_meta = SUPPORTED_LANGUAGES.get(lang, {})
        # Phase 1.2.3: render the same `version_tip` the wizard prints
        # as a comment block above `version =`. DRY — one source string
        # in SUPPORTED_LANGUAGES, two consumers (wizard + this TOML).
        # Users editing the file later see the same guidance the wizard
        # gave them.
        version_tip = lang_meta.get("version_tip")
        if version_tip:
            import textwrap

            lines += textwrap.wrap(
                version_tip,
                width=76,
                initial_indent="# ",
                subsequent_indent="# ",
                break_long_words=False,
                break_on_hyphens=False,
            )
        lines.append(f"version = {_format_toml_string(cfg['version'])}")
        # Phase 1.2.4: same DRY pattern for `manager_tip` — comment block
        # above `manager =`. The `manager` line itself is now ALWAYS
        # emitted (resolved value: user pick or language default), no
        # longer gated on whether the user overrode the default.
        manager_tip = lang_meta.get("manager_tip")
        if manager_tip:
            import textwrap

            lines += textwrap.wrap(
                manager_tip,
                width=76,
                initial_indent="# ",
                subsequent_indent="# ",
                break_long_words=False,
                break_on_hyphens=False,
            )
        manager = cfg.get("manager") or lang_meta.get("default_manager")
        if manager:
            lines.append(f"manager = {_format_toml_string(manager)}")
        lines.append("")
    # One commented syntax-reference block for a language the user DIDN'T
    # pick. If they picked all four, fall back to python as a generic
    # reference (copy-paste-able).
    example_lang = next(
        (lang for lang in _EXAMPLE_LANGUAGE_BLOCKS if lang not in languages),
        "python",
    )
    lines += _EXAMPLE_LANGUAGE_BLOCKS[example_lang]
    lines.append("")

    # --- [startup] ------------------------------------------------------
    lines += _STARTUP_SECTION_COMMENT
    startup_commands = data.get("startup", {}).get("commands", [])
    if startup_commands:
        lines.append("[startup]")
        lines.append(f"commands = {_format_toml_list(startup_commands)}")
    else:
        lines += _STARTUP_EXAMPLE

    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def write_coding_environment_toml(project_dir: Path, data: dict, overwrite: bool = False) -> Path:
    """Write coding-environment.toml at repo root.

    Default: append a hex suffix if the canonical filename already exists,
    so user-authored content is never clobbered. Phase 1.2.3 added the
    `overwrite=True` opt-in: when `cmd_init` has confirmed the existing
    file is alcatrazer-generated AND the user accepted overwrite, we
    write to the canonical name instead. Reuse-path (user accepted "reuse
    as-is") doesn't go through this function at all.
    """
    target = project_dir / "coding-environment.toml"
    if target.exists() and not overwrite:
        suffix = secrets.token_hex(2)
        target = project_dir / f"coding-environment-{suffix}.toml"
    target.write_text(_render_coding_environment(data))
    return target


def write_alcatrazer_config(
    project_dir: Path,
    name: str,
    email: str,
    coding_env_file: str = "coding-environment.toml",
) -> Path:
    """Write .alcatrazer/config.toml by line-rewriting the packaged template."""
    alcatrazer_dir = project_dir / ".alcatrazer"
    alcatrazer_dir.mkdir(parents=True, exist_ok=True)
    template_path = Path(__file__).parent / "templates" / "alcatrazer-config.toml"
    out_lines: list[str] = []
    for line in template_path.read_text().splitlines():
        if line.startswith("coding_environment_file = "):
            out_lines.append(f"coding_environment_file = {_format_toml_string(coding_env_file)}")
        elif line.startswith("name = "):
            out_lines.append(f"name = {_format_toml_string(name)}")
        elif line.startswith("email = "):
            out_lines.append(f"email = {_format_toml_string(email)}")
        else:
            out_lines.append(line)
    target = alcatrazer_dir / "config.toml"
    target.write_text("\n".join(out_lines) + "\n")
    return target


_ENV_EXAMPLE_HEADER = (
    "# Example environment variables for this project.\n"
    "# Copy to .env and fill in your values.\n"
    "# .env should stay out of version control; .env.example is committed.\n"
)


def _env_example_markers(workspace_name: str) -> tuple[str, str]:
    """Build begin/end markers from the workspace name (leading dot stripped).

    Using the workspace name keeps this file free of any "alcatraz"
    branding — .env.example gets committed to the outer repo AND
    snapshotted into /workspace, so the agent can read it. The workspace
    name is a neutral hex-suffixed tag, stable within a single repo,
    which gives us a collision-resistant identifier for idempotent
    in-place rewrites on re-run.
    """
    tag = workspace_name.lstrip(".")
    return (f"# --- {tag} begin ---", f"# --- {tag} end ---")


def _env_example_block(workspace_name: str) -> str:
    begin, end = _env_example_markers(workspace_name)
    return (
        f"{begin}\n"
        "# AI API key; picked up when the workspace starts.\n"
        "# Only needed if you haven't authenticated Claude on your host\n"
        "# (~/.claude/.credentials.json). Uncomment and fill in.\n"
        "#ANTHROPIC_API_KEY=\n"
        f"{end}\n"
    )


def write_env_example(project_dir: Path, workspace_name: str) -> Path:
    """Write/update `.env.example` at the repo root with a credentials block.

    The block is bracketed by markers derived from `workspace_name` so the
    file contains zero alcatraz / alcatrazer strings. Prose inside the
    block is backend-agnostic ("workspace", not "container").

    Three cases:
      - No file: write header + block.
      - File without our markers: append the block at the end, leave
        existing content untouched.
      - File with our markers: replace the block in place (idempotent).
    """
    begin, end = _env_example_markers(workspace_name)
    block = _env_example_block(workspace_name)
    target = project_dir / ".env.example"

    if not target.exists():
        target.write_text(_ENV_EXAMPLE_HEADER + "\n" + block)
        return target

    existing = target.read_text()
    if begin in existing and end in existing:
        begin_idx = existing.index(begin)
        end_idx = existing.index(end) + len(end)
        updated = existing[:begin_idx] + block.rstrip() + existing[end_idx:]
        target.write_text(updated)
        return target

    separator = "" if existing.endswith("\n") else "\n"
    target.write_text(existing + separator + "\n" + block)
    return target


def run_startup_commands(prison: Alcatraz, commands: list[str]) -> int:
    """Run each `[startup]` command inside the prison, fail-fast on first error.

    Each toml entry is a single shell string, so it is invoked as
    `bash -c <cmd>` — lets pipes, redirections, and multi-word commands
    behave as the user wrote them. Progress goes to stdout; on failure a
    pointer to the offending index + command goes to stderr. Returns 0 on
    full success or the failing exit code.
    """
    for i, cmd in enumerate(commands, 1):
        print(f"→ Running startup command #{i}: {cmd}")
        rc = prison.exec(["bash", "-c", cmd])
        if rc != 0:
            print(
                f"ERROR: startup command #{i} failed ({cmd!r}) — exit {rc}.",
                file=sys.stderr,
            )
            print(
                "→ Check the [startup] block in coding-environment.toml.",
                file=sys.stderr,
            )
            return rc
    return 0


def save_coding_environment_snapshot(project_dir: Path) -> Path:
    """Copy the current coding-environment file to .alcatrazer/coding-environment.toml.last.

    The source filename is read from .alcatrazer/config.toml's
    `coding_environment_file` pointer (supports hex-suffixed collisions).
    The target name is always canonical (`coding-environment.toml.last`),
    so Step 4 can diff against a fixed path.
    """
    alcatrazer_dir = project_dir / ".alcatrazer"
    with open(alcatrazer_dir / "config.toml", "rb") as f:
        config = tomllib.load(f)
    source_name = config.get("coding_environment_file", "coding-environment.toml")
    source = project_dir / source_name
    target = alcatrazer_dir / "coding-environment.toml.last"
    shutil.copy(source, target)
    return target


def create_workspace(project_dir: Path, workspace_name: str) -> Path:
    """Create the inner workspace for the agent (Step 3j).

    - Creates `project_dir / workspace_name` (the leading dot is expected
      to be part of `workspace_name`, matching identity.generate_workspace_dir_name).
    - `git init`s it with a fresh history disconnected from the outer repo.
    - Generates + persists the random agent identity (or reuses an existing
      one) via identity.ensure_identity.
    - Wires the workspace-local git config: user.name / user.email from the
      stored identity, `commit.gpgsign false`; clears any host signing-key
      path so host state does not leak into the inner repo.
    - Takes a flat snapshot of the outer repo's default branch via
      snapshot.snapshot_workspace — files only, no history, single initial
      commit authored by the agent identity.

    Returns the workspace directory path.
    """
    workspace_dir = project_dir / workspace_name
    alcatrazer_dir = project_dir / ".alcatrazer"
    alcatrazer_dir.mkdir(parents=True, exist_ok=True)
    workspace_dir.mkdir(parents=True, exist_ok=True)

    subprocess.run(
        ["git", "init", str(workspace_dir)],
        capture_output=True,
        check=True,
    )

    name, email = identity.ensure_identity(str(alcatrazer_dir))

    def _wgit(*args: str) -> None:
        subprocess.run(
            ["git", "-C", str(workspace_dir), *args],
            capture_output=True,
            check=True,
        )

    _wgit("config", "--local", "user.name", name)
    _wgit("config", "--local", "user.email", email)
    _wgit("config", "--local", "commit.gpgsign", "false")
    # Defensive: clear any host signing-key references so they cannot leak
    # into the inner repo's config.
    _wgit("config", "--local", "user.signingkey", "")
    _wgit("config", "--local", "gpg.ssh.allowedSignersFile", "")

    snapshot.snapshot_workspace(str(project_dir), str(workspace_dir))

    return workspace_dir


def write_python_symlink(project_dir: Path) -> Path:
    """Symlink `.alcatrazer/python` → `sys.executable`.

    Gives the post-install daemon (and any other tooling that needs to call
    back into a host Python) a stable path to the resolved interpreter,
    independent of the user's shell at run time.
    """
    alcatrazer_dir = project_dir / ".alcatrazer"
    alcatrazer_dir.mkdir(parents=True, exist_ok=True)
    target = alcatrazer_dir / "python"
    if target.is_symlink() or target.exists():
        target.unlink()
    target.symlink_to(sys.executable)
    return target


_PACKAGE_IGNORE_PATTERNS = ("__pycache__", "*.pyc", "*.pyo")


def extract_package_source(
    project_dir: Path,
    source_dir: Path | None = None,
) -> Path:
    """Copy the alcatrazer package tree into .alcatrazer/src/alcatrazer/.

    Gives the user readable source and bundled tests. Compiled artifacts
    (__pycache__, .pyc, .pyo) are skipped. If the destination already
    exists (e.g., on re-run or during `alcatrazer upgrade`), it is removed
    first so stale files cannot linger from an older version.

    `source_dir` defaults to the installed package directory (Step 6
    upgrade passes a freshly-downloaded wheel's extracted tree instead).
    """
    if source_dir is None:
        source_dir = Path(__file__).parent
    dest = project_dir / ".alcatrazer" / "src" / "alcatrazer"
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source_dir, dest, ignore=shutil.ignore_patterns(*_PACKAGE_IGNORE_PATTERNS))
    return dest


_GIT_EXCLUDE_HEADER = "# alcatrazer patterns (written by alcatrazer init)"


def write_git_exclude(project_dir: Path, workspace_name: str) -> Path:
    """Append alcatrazer + workspace patterns to .git/info/exclude, idempotently.

    `workspace_name` is used verbatim (callers pass the full directory name,
    typically from `alcatrazer.identity.generate_workspace_dir_name()` which
    already includes the leading dot). We just append a trailing slash to
    form the directory pattern.
    """
    exclude_path = project_dir / ".git" / "info" / "exclude"
    exclude_path.parent.mkdir(parents=True, exist_ok=True)
    existing = exclude_path.read_text() if exclude_path.exists() else ""
    existing_lines = set(existing.splitlines())

    patterns = (".alcatrazer/", f"{workspace_name}/")
    missing = [p for p in patterns if p not in existing_lines]
    if not missing:
        return exclude_path

    prefix = existing
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    exclude_path.write_text(prefix + _GIT_EXCLUDE_HEADER + "\n" + "\n".join(missing) + "\n")
    return exclude_path


def coding_environment_changed(project_dir: Path) -> bool:
    """True when the current coding-environment file differs from .last.

    The source filename is read from .alcatrazer/config.toml's
    `coding_environment_file` pointer (supports hex-suffixed collisions).
    `.last` missing counts as changed.
    """
    alcatrazer_dir = project_dir / ".alcatrazer"
    with open(alcatrazer_dir / "config.toml", "rb") as f:
        config = tomllib.load(f)
    source = project_dir / config.get("coding_environment_file", "coding-environment.toml")
    last = alcatrazer_dir / "coding-environment.toml.last"
    if not last.exists():
        return True
    return source.read_text() != last.read_text()


def _normalize_env_content(text: str) -> bytes:
    """Strip what the Alcatraz will never see: blank lines and full-line
    comments (leading whitespace + `#`). Preserves line order and
    preserves inline `# ...` tails on `KEY=VALUE` lines because docker's
    `--env-file` treats them as part of the value.

    Returned as UTF-8 bytes so the caller can hash directly.
    """
    kept: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        kept.append(line.rstrip())
    return "\n".join(kept).encode("utf-8")


def _env_hash(env_path: Path) -> str:
    """SHA256 of `.env`'s normalized content. Empty string if absent."""
    if not env_path.exists():
        return ""
    return hashlib.sha256(_normalize_env_content(env_path.read_text())).hexdigest()


def env_file_changed(project_dir: Path) -> bool:
    """True when `.env` has meaningfully changed since the last snapshot.

    Decision table (see install_method.md Step 4c):
      - absent .env + absent .hash.last → False (greenfield)
      - absent .env + present .hash.last → True (user removed .env)
      - present .env + matching hash → False
      - otherwise → True
    """
    env_path = project_dir / ".env"
    last_path = project_dir / ".alcatrazer" / "env.hash.last"
    env_present = env_path.exists()
    last_present = last_path.exists()
    if not env_present and not last_present:
        return False
    if not env_present and last_present:
        return True
    if not last_present:
        return True
    return last_path.read_text().strip() != _env_hash(env_path)


def save_env_snapshot(project_dir: Path) -> Path | None:
    """Persist the current `.env` hash to `.alcatrazer/env.hash.last`.

    Symmetric with `save_coding_environment_snapshot`, with one wrinkle:
    if `.env` is absent, we **delete** any existing `.hash.last` rather
    than writing a sentinel — that keeps `env_file_changed`'s "both
    absent → unchanged" branch honest on subsequent runs.
    """
    env_path = project_dir / ".env"
    last_path = project_dir / ".alcatrazer" / "env.hash.last"
    if not env_path.exists():
        if last_path.exists():
            last_path.unlink()
        return None
    last_path.parent.mkdir(parents=True, exist_ok=True)
    last_path.write_text(_env_hash(env_path) + "\n")
    return last_path


def _load_coding_environment(project_dir: Path) -> dict:
    """Read config.toml pointer + parse + validate the coding-environment file.

    Schema version is checked via _validate_coding_env_schema_version so that
    a newer config never gets silently misread by an older alcatrazer. Files
    without an explicit schema_version field are accepted (treated as v1) so
    configs written before Phase 1.1 keep working unchanged.
    """
    alcatrazer_dir = project_dir / ".alcatrazer"
    with open(alcatrazer_dir / "config.toml", "rb") as f:
        config = tomllib.load(f)
    source = project_dir / config.get("coding_environment_file", "coding-environment.toml")
    with open(source, "rb") as f:
        data = tomllib.load(f)
    _validate_coding_env_schema_version(data)
    return data


def cmd_selftest(project_dir: Path) -> int:
    """Run `--run-selftest`: execute the bundled security invariants against
    the Alcatraz just started at `project_dir`. Returns 0 on success or
    non-zero on failure (count of failures is shown by the test runner)."""
    from alcatrazer import selftest

    TestCase = selftest.make_alcatraz_selftest_testcase(project_dir)
    suite = unittest.TestLoader().loadTestsFromTestCase(TestCase)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


def cmd_visit(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """`alcatrazer visit` — open an interactive shell as agent inside the
    running Alcatraz.

    Phase 1.2.5. Replaces the old README incantation
    ``docker exec -it -u agent -w /workspace workspace bash``, which
    stopped working when per-repo container names landed.

    Errors explicitly when:

    - ``.alcatrazer/`` is missing → user hasn't run ``alcatrazer init``.
    - The Alcatraz isn't running → user must run ``alcatrazer start``
      first. No auto-start: that would hide rebuilds and daemon launches
      under what should be a fast "drop me in" command.

    On success ``prison.shell()`` replaces this Python process via
    ``os.execvp`` and never returns; the explicit ``return 0`` below is
    unreachable but keeps the type checker happy.
    """
    if not (project_dir / ".alcatrazer").exists():
        print(
            "No alcatrazer setup in this repository — run `alcatrazer init` first.",
            file=sys.stderr,
        )
        return 1
    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)
    if not prison.is_running():
        print(
            "Alcatraz is not running — run `alcatrazer start` first.",
            file=sys.stderr,
        )
        return 1
    prison.shell()  # replaces the process via execvp; never returns
    return 0


def cmd_clear(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """`alcatrazer clear` — throw away the Alcatraz runtime, preserve
    the workspace.

    Removes the container so its writable overlay layer and any caches
    living there are discarded. Preserves:
    - the image (so `alcatrazer start` doesn't need to rebuild),
    - `.alcatrazer/` config,
    - the Alcatraz workspace (`project_dir/<workspace-name>/`) on the
      host filesystem — this is where agent work lives, and it's safe
      to keep because commits that synced already live in your
      repository too, and any unsynced commits are preserved here for
      next-start recovery,
    - user repo-root files (`coding-environment.toml`, `.env`,
      `.env.example`).

    Ordering (Step 5.7 non-negotiable rule, same as cmd_stop):
    1. `docker stop` — agents frozen.
    2. `shutdown_sync_daemon` — daemon runs final sync against the
       frozen inner repo, exits. Any commits it can't sync stay in
       the workspace via the paused-branches machinery.
    3. `docker rm` — container gone.

    Idempotent: missing Alcatraz is reported as "nothing to clear" and
    returns 0. Final sync conflict / failure / timeout still proceeds
    with docker rm (unsynced commits live in the preserved workspace)
    but returns non-zero so the user is aware.
    """
    if not (project_dir / ".alcatrazer").exists():
        print(
            "No alcatrazer setup in this repository — run `alcatrazer init` first.",
            file=sys.stderr,
        )
        return 1

    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    # Step 1 — docker down first.
    if prison.is_running():
        prison.stop()

    # Step 2 — daemon final sync + exit. Called even when the Alcatraz
    # is already gone so a lingering daemon against a user-removed
    # container (rare but possible) is reaped cleanly and state.json's
    # flag is closed.
    result = shutdown_sync_daemon(project_dir)
    print_shutdown_result(result)

    # Step 3 — discard the container.
    if prison.exists():
        prison.remove()
        print("Alcatraz cleared — Alcatraz workspace preserved on the host.")
    else:
        print("Nothing to clear — Alcatraz not present.")

    if result.outcome in ("conflict", "failed", "timeout"):
        return 1
    return 0


def cmd_stop(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """`alcatrazer stop` — freeze the Alcatraz + shut down the sync daemon.

    Ordering (non-negotiable, see Step 5.7 in install_method.md):
    docker stop FIRST, then daemon shutdown. Any other order reopens a
    race: an agent commit between the daemon's last poll and our
    SIGTERM would get synced just before docker stop — and any commit
    that landed AFTER the final sync but before `docker stop` would
    stay in the Alcatraz workspace unsynced. Stopping docker first
    means "no more commits possible" when the daemon finalizes.

    Returns:
      0 — everything went as planned.
      1 — no `.alcatrazer/` setup (user hasn't run `alcatrazer init`).
      1 — daemon final sync had a conflict, failed, or timed out
          (Alcatraz is still stopped, daemon is gone; user resolves in
          their repository, then `alcatrazer start` resumes).
    """
    if not (project_dir / ".alcatrazer").exists():
        print(
            "No alcatrazer setup in this repository — run `alcatrazer init` first.",
            file=sys.stderr,
        )
        return 1

    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    # Step 1 — docker down first (agents frozen).
    if prison.is_running():
        prison.stop()
        print("Alcatraz stopped.")
    else:
        print("Alcatraz is not running.")

    # Step 2 — daemon shutdown against the now-frozen inner repo. Always
    # call this, even if the Alcatraz was already stopped: a lingering
    # daemon against a stopped container is still worth reaping, and
    # shutdown_sync_daemon also cleans up the state.json flag from any
    # prior cycle.
    result = shutdown_sync_daemon(project_dir)
    print_shutdown_result(result)

    if result.outcome in ("conflict", "failed", "timeout"):
        return 1
    return 0


def _subsequent_run(project_dir: Path, prison: Alcatraz | None = None) -> int:
    """Bring the Alcatraz into sync with the current config, recreating
    it ONLY when a change actually invalidates the writable layer.

    Five-case lifecycle (see install_method.md "Ephemeral caches" + Step 4):

      1. Fast path     — running + no changes → no-op.
      2. Full recreate — rebuild OR env_changed → stop/remove/(build)/start.
         Writable layer + caches cleared, but that's correct: the image or
         baked env that shaped the cache changed, so stale cache would be
         wrong anyway.
      3. Resume stopped — exists + !running + no recreate signals →
         `docker start`, preserves the writable overlay layer (and its
         mise/pip/npm caches). The cache-preservation branch.
      4. Startup-only on running — running + toml_changed + no recreate
         signals → keep container, re-run `[startup]` via `exec`. Zero
         disruption, zero cache loss.
      5. Fresh start — !exists → user externally `docker rm`'d. Falls
         through to a plain `start()` (no stop/remove needed — nothing
         to stop). Equivalent to first-run-after-init.

    `.last` snapshots (coding-env + env hash) refresh only on startup
    success so a retry sees the same drift signals.
    """
    if prison is None:
        from alcatrazer.docker_prison import DockerPrison

        prison = DockerPrison(project_dir)

    coding_env = _load_coding_environment(project_dir)
    commands = coding_env.get("startup", {}).get("commands", [])

    rebuild = prison.needs_rebuild(coding_env)
    toml_changed = coding_environment_changed(project_dir)
    env_changed = env_file_changed(project_dir)
    running = prison.is_running()
    exists = prison.exists()

    # Case 1: fast path.
    if running and not rebuild and not toml_changed and not env_changed:
        print("Already running, environment up to date.")
        # Self-heal: ensure the sync daemon is alive (relaunch silently
        # if a stale PID pointed at a dead process).
        launch_daemon_and_print(project_dir)
        return 0

    # Case 2: full recreate (rebuild or env_changed).
    if rebuild or env_changed:
        if rebuild:
            print("coding-environment.toml changed — rebuilding image.")
            prison.generate_prison(coding_env)
        else:
            print(".env changed — recreating the Alcatraz.")
        if running:
            prison.stop()
        if exists:
            prison.remove()
        if rebuild:
            prison.build()
        try:
            prison.start()
        except PrisonStartError as e:
            print("ERROR: Alcatraz start failed.", file=sys.stderr)
            if e.stdout:
                print(e.stdout, file=sys.stderr)
            if e.stderr:
                print(e.stderr, file=sys.stderr)
            return 1
    # Case 5: fresh start (container gone).
    elif not exists:
        print("Starting Alcatraz...")
        try:
            prison.start()
        except PrisonStartError as e:
            print("ERROR: Alcatraz start failed.", file=sys.stderr)
            if e.stdout:
                print(e.stdout, file=sys.stderr)
            if e.stderr:
                print(e.stderr, file=sys.stderr)
            return 1
    # Case 3: resume stopped.
    elif not running:
        print("Resuming Alcatraz...")
        try:
            prison.resume()
        except PrisonStartError as e:
            print("ERROR: Alcatraz resume failed.", file=sys.stderr)
            if e.stdout:
                print(e.stdout, file=sys.stderr)
            if e.stderr:
                print(e.stderr, file=sys.stderr)
            return 1
    # Case 4: running + toml_changed (startup-only change) — fall through
    # with the container still up; we'll just re-run startup commands
    # against it below.

    rc = run_startup_commands(prison, commands)
    if rc == 0:
        save_coding_environment_snapshot(project_dir)
        save_env_snapshot(project_dir)
        launch_daemon_and_print(project_dir)
    return rc
